### ISSUE TITLE
Division sign (slash) is confused with multiline comment

### ISSUE THREAD

**Issue by khaled-ek** [lark-parser/lark#768] opened 2020-11-19 16:43 UTC
Hello,

I listed below a snapshot of my rules for parsing binary operation:

``` python

binary_operation: sum_operation

sum_operation: mul_operation
    | sum_operation PLUS mul_operation  -> add
    | sum_operation MINUS mul_operation -> minus
    
mul_operation: power_operation      
    | mul_operation MULTIPLICATION power_operation  -> mul
    | mul_operation DIVISION power_operation        -> div
    
power_operation: new_expression
    | power_operation POWER expression  -> power

expression: constant
		| reference

reference: name
 
name: ID | quoted_identifier

ID: /[A-Za-z][A-Za-z0-9\d_]*/
	
PLUS: "+"
DIVISION: "/"
MINUS: "-"
POWER : "^"
MULTIPLICATION: "*"

MULTILINE_COMMENT: /\/\*.*?\*\//s

%ignore MULTILINE_COMMENT
%ignore /\s/s
```

The rules work well when parsing the expression:
```
x/**/:=/**/(1.00000000000000002E-02/**/*y)
```
But parsing the following expression results in the error below:
```
x/**/:=/**/(y/**// 4.0)
```

lark.exceptions.UnexpectedCharacters: No terminal defined for '/' at line
Expecting: {'MINUS', 'PLUS', 'MULTIPLICATION', 'POWER'}

Any help would be much appreciated,

Best regards

**Comment by ThatXliner** [comment] 2020-11-19 16:52
One thing, the `MULTILINE_COMMENT` is already implemented in the standard library right here:

https://github.com/lark-parser/lark/blob/dc22f2218f4cad77b1d191d6cef76d3476a50138/lark/grammars/common.lark#L57

**Comment by khaled-ek** [comment] 2020-11-19 17:02
The CPP_COMMENT did not work for parsing multiline comments in my case, but I have no problems in parsing multiline comments anyway. I have the problem which I reported above.

**Comment by ThatXliner** [comment] 2020-11-19 17:15
Sorry, I didn't realize you wanted
https://github.com/lark-parser/lark/blob/dc22f2218f4cad77b1d191d6cef76d3476a50138/lark/grammars/common.lark#L58
instead

**Comment by MegaIng** [comment] 2020-11-19 19:51
Please give an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example). Your issue leads to a lot of open questions:

- The grammar isn't complete. There are a few rules referenced that you didn't post.
- Which parser did you use?
- Which lexer did you use?

I can also see that what you posted there can't be the exact grammar you are using (or we have an incredible severe bug in Lark somewhere that should prevent most grammars from working). Otherwise `DIVIDE` would have to appear in the `Expected` list.

We are certainly ready and open to help you, but you didn't give us enough information.

**Comment by khaled-ek** [comment] 2020-11-20 15:05
You are absolutely right, grammar is not complete. I actually provided a snapshot of the rules.

I added now a minimal example which produces the same error:

```python
from lark import Lark

l = Lark(r'''start: single_assignment

single_assignment: reference ASSIGNMENT binary_operation

binary_operation: sum_operation

sum_operation: mul_operation
    | sum_operation PLUS mul_operation  -> add
    | sum_operation MINUS mul_operation -> minus
    
mul_operation: power_operation      
    | mul_operation MULTIPLICATION power_operation  -> mul
    | mul_operation DIVISION power_operation        -> div
    
power_operation: expression
    | power_operation POWER expression  -> power

expression: constant
    | reference

reference: name

constant: NUMBER

name: ID

ID: /[A-Za-z][A-Za-z0-9\d_]*/

PLUS: "+"
DIVISION: "/"
MINUS: "-"
POWER : "^"
MULTIPLICATION: "*"

MULTILINE_COMMENT: /\/\*.*?\*\//s

ASSIGNMENT: ":="



%import common.NUMBER

%ignore MULTILINE_COMMENT
%ignore /\s/s

''', parser="earley")


p = l.parse("x/**/:=/**/y/**// 4.0")
#p = l.parse("x/**/:=/**/1.00000000000000002E-02/**/*y")
```

**Comment by ThatXliner** [comment] 2020-11-20 16:22
With inlining the grammar

```lark
start: single_assignment

single_assignment: reference ASSIGNMENT binary_operation

?binary_operation: sum_operation

?sum_operation: mul_operation
    | sum_operation PLUS mul_operation  -> add
    | sum_operation MINUS mul_operation -> minus
    
?mul_operation: power_operation      
    | mul_operation MULTIPLICATION power_operation  -> mul
    | mul_operation DIVISION power_operation        -> div
    
?power_operation: expression
    | power_operation POWER expression  -> power

?expression: constant
    | reference

?reference: name

?constant: NUMBER

?name: ID

ID: /[A-Za-z][A-Za-z0-9\d_]*/

PLUS: "+"
DIVISION: "/"
MINUS: "-"
POWER : "^"
MULTIPLICATION: "*"

MULTILINE_COMMENT: /\/\*.*?\*\//s

ASSIGNMENT: ":="



%import common.NUMBER

%ignore MULTILINE_COMMENT
%ignore /\s/s
```
and removing the comments
```
x:=y/4.0
```
I got this tree from the [online ide](https://lark-parser.github.io/lark/ide/app.html) (hey that rhymes):
<img width="236" alt="Screen Shot 2020-11-20 at 8 22 04 AM" src="https://user-images.githubusercontent.com/66848002/99823635-7a362180-2b09-11eb-8574-afd2ce79bceb.png">

**Comment by MegaIng** [comment] 2020-11-20 16:33
This is a bug in the dynamic/dynamic_complete lexer. I don't know enough about earley to analise this, but it is incredibly confusing. Here is an even more reduced example:

```python
from lark import Lark

l = Lark(r'''
start: constant | constant DIVISION constant

constant: NUMBER

DIVISION: "#"

MULTILINE_COMMENT: "#**#"

POWER: "^"

%import common.NUMBER

%ignore MULTILINE_COMMENT
%ignore /\s/s
''', parser="earley")


p = l.parse("5#**# # 4")

print(p.pretty())
```

As you can see, it is nothing special about `/`. Just the symbol of the ignored and the divison need to be the same.

The problem appears to be that earley is wrongly folding the `constant` option of `start`. But in my understanding, earley doesn't even do any folding.

So yes, this is an incredible severe bug in Lark.
--- 

> and removing the comments

Yes, removing the source of the bug removes the bug...

**Comment by MegaIng** [comment] 2020-11-20 16:36
@khaled-ek As a workaround, use `lexer='standard'` or `parser='lalr'`  when possible (Don't use both).

**Comment by ThatXliner** [comment] 2020-11-20 16:48
`5##**#4` works. I assume it's because that it doesn't lookahead deciding if it should skip the token or not

**Comment by MegaIng** [comment] 2020-11-20 17:22
> I assume it's because that it doesn't lookahead deciding if it should skip the current token or not

In my understanding, _this is not how earley works_. So how can it get this wrong?

**Comment by ThatXliner** [comment] 2020-11-20 17:40
What's the precedence of `|`?

**Comment by MegaIng** [comment] 2020-11-20 17:41
Can't be a problem. The grammar works perfect with lalr.

**Comment by chanicpanic** [comment] 2020-11-24 00:49
I have done some debugging and found that these examples work after deleting [line 68 of xearley.py](https://github.com/lark-parser/lark/blob/e6dcc434786a1f3a4e53581673e05c6663fcef16/lark/parsers/xearley.py#L68): `to_scan.remove(item)`

Also, all existing tests pass. Can anyone come up with an example that is broken by this change? The comments seem to suggest that there may be a case in which this line is necessary.

**Comment by erezsh** [comment] 2020-11-24 13:18
@chanicpanic That line and comments were added by @night199uk . I wish he would be able to comment on it, but he hasn't been available lately.

If removing that line doesn't create any detectable problem, then maybe it really shouldn't be there.

**Comment by MegaIng** [comment] 2020-11-24 13:32
From my reading of the comment, the line exist to specifically break this situation. It prevents terminals from being matched again after an ignored token. I don't know why though.

**Comment by khaled-ek** [comment] 2020-11-24 16:56
@MegaIng If you think that the latest omission resolves the bug, will you make this fixed version available on PyPI any soon?

Thanks

**Comment by MegaIng** [comment] 2020-11-24 17:37
I am not the maintainer. That is @erezsh .

**Comment by erezsh** [comment] 2020-11-24 18:41
@khaled-ek We haven't fixed it yet. We're still debating whether it's wise to remove that line or not.

After we fix it, we will make a release in due time.

But even before the release, you can install the latest `master` using: `python -m pip install git+https://github.com/lark-parser/lark.git`

**Comment by charles-esterbrook** [comment] 2020-11-25 15:35
For what it's worth, I ran into the same problem as @khaled-ek, I just hadn't spent any time on it, so was unsure if I was doing something wrong or had encountered a bug.

**Comment by MegaIng** [comment] 2020-11-26 14:37
Suggestion: Make the fix by commenting out those lines. Add an additional comment explaing the situation and referencsing this issue. We don't have any test that tell us this is required. If we roll this out and it breaks something, we need a new test case.

For me this looks like an optimization: If we already know this Token can match at this point, why should we try again later? Sadly, it breaks stuff.

**Comment by erezsh** [comment] 2020-11-27 08:47
I went with @MegaIng 's suggestion.

@khaled-ek @charles-esterbrook This is now fixed in `master`, and will be there in the next release.

Hopefully it won't break anyone's code.

**Comment by charles-esterbrook** [comment] 2020-11-27 13:17
Thanks!

**Comment by khaled-ek** [comment] 2020-11-27 19:20
Thank you guys

**Closed** 2021-06-29 15:20 UTC
Labels: bug
