### ISSUE TITLE
v_args decorator calls FunctionType function with self.

### ISSUE THREAD

**Issue by guyd** [lark-parser/lark#249] opened 2018-10-15 14:50 UTC
When decorating a `Transformer` with v_args, the decorated functions are called with self even for non-method.

The last parameter at this line should be False, isn't it?
https://github.com/lark-parser/lark/blob/master/lark/utils.py#L63

**Comment by erezsh** [comment] 2018-10-15 16:57
I'm not sure. I'll have to set up a few tests to see what's the correct behavior.

Duplicate of #246

**Comment by erezsh** [comment] 2018-10-15 16:58
Btw, if you want to write a test encompassing all the possibilities (method, static, clsmethod, lambda, etc.) that would be great.

**Closed by erezsh** 2018-10-15 16:57 UTC

**Comment by erezsh** [comment] 2018-10-16 11:33
Fixed in `master` and version 0.6.5

**Comment by guyd** [comment] 2018-10-16 14:05
Thanks for the quick fix. However, I think that the fix is a bit more involved. For example, these small changes to your newly added test will break
```
 def test_vargs(self):
        @v_args(inline=True)
        class MyTransformer(Transformer):
            @staticmethod
            def integer():
                return 1 # some code here

            @classmethod
            def integer2(cls):
                return 2 # some code here

            hello = staticmethod(lambda: 'hello')

            def integer3(self):
                return 3

        x = MyTransformer().transform( Tree('integer', []))
        self.assertEqual(x, 1)
        x = MyTransformer().transform( Tree('integer2', []))
        self.assertEqual(x, 2)
        x = MyTransformer().transform(Tree('integer3', []))
        self.assertEqual(x, 3)
        x = MyTransformer().transform( Tree('hello', []))
        self.assertEqual(x, 'hello')
```
My understanding of the problem is that since python 3 removed the distinction between unbound method and function, it is tricky to determine how a class method should be called.

**Comment by erezsh** [comment] 2018-10-17 08:44
Thanks for pointing that out.

Actually, it's just that my fix was incorrect. Everything should work now (on `master`)

**Comment by guyd** [comment] 2018-10-17 12:03
Great. Thanks again. I will git it a try.
