### ISSUE TITLE
Enhancement: Higher Importance for custom error handling.

### ISSUE THREAD

**Issue by techpixel** [lark-parser/lark#644] opened 2020-08-10 20:12 UTC
Lark's current error handling method loops through a dictionary, with the first items in the dict having higher importance than the last. 
Instead of this current method, implement a new method which allows users to set a higher importance for errors. It helps make code much more organized and easier to understand.

**But, where would this come in play?**
Let's say I have a grammar where all expressions would end in a semicolon.
Here is the grammar:
```py
exc_class = u.match_example( parser.parse, {
        MissingBracket : [
          '( 1 + 1',
          '( 1 + 1 ;',
          '1 + 1 )'
        ],
        MissingSemicolon : [
          '1 + 1',
          '1 + 1;;'
        ],
        })
```
But when I parse this code: `1 + 1`, it would raise a MissingBracket instead of a MissingSemicolon
Currently, the only way to fix this is by having the less important error matches pushed to the back like so:
```py
exc_class = u.match_example( parser.parse, {
        MissingBracket : [
          '( 1 + 1',
          '( 1 + 1 ;',
        ],
        MissingSemicolon : [
          '1 + 1',
          '1 + 1;;'
        ],
        MissingBracket : [
          '1 + 1 )'
        ]
        })
```
However, through this way you would have less organized code, and it would be much simpler having some sort of way to set a error example with more importance.

**Comment by MegaIng** [comment] 2020-08-10 20:15
Can you give a full example script?

**Comment by techpixel** [comment] 2020-08-10 20:18
```py
from lark import Lark, Transformer, UnexpectedInput
import argparse, os

#argparse

argparser = argparse.ArgumentParser(description='Run the Zala Program')

argparser.add_argument("-f", "--file", action="store", help="run the file")
argparser.add_argument("-r", "--repl", action="store_true", help="enter REPL mode")

args = argparser.parse_args()

parser = Lark.open('zala.lark', rel_to=__file__, parser='lalr', regex=True) #lark parser


# Transformer

class Ztransformer(Transformer):
  NUMBER = int
  FLOAT = float

  def add(self, args):
    return args[0] + args[1]
  
  def sub(self, args):
    return args[0] - args[1]
  
  def mul(self, args):
    return args[0] * args[1]
  
  def div(self, args):
    return args[0] / args[1]
  
  def neg(self, args):
    return -args[0]
  
  def pow(self, args):
    return args[0] ** args[1]

  def start(self, args):
    for arg in args:
      print(str(arg))
    return ""

# Errors

class ZalaSyntaxError(SyntaxError):
  def __str__(self):
    context, line, column = self.args
    return '%s at line %s, column %s.\n\n%s' % (self.label, line, column, context)

  def return_exception(self):
    context, line, column = self.args
    return '%s at line %s, column %s.\n\n%s' % (self.label, line, column, context)

class MissingSemicolon(ZalaSyntaxError):
    label = 'Missing Semicolon' 
class MissingBracket(ZalaSyntaxError):
    label = 'Missing Bracket' 

def repl():
  os.system('clear')
  print('Zala 0.1 release')
  while True:
    try:
      inputCode = input('\033[38;2;255;119;0m \033[0;0m')
    except KeyboardInterrupt:
      os.system('clear')
      argparser.exit(status=0, message="Left REPL mode.\n")
    try:
      tree = parser.parse(inputCode)
      result = Ztransformer(visit_tokens = True).transform(tree)
      print(result)
    except UnexpectedInput as u:
      exc_class = u.match_examples(parser.parse,
      {
        MissingBracket : [
          '( 1 + 1',
          '( 1 + 1 ;',
        ],
        MissingSemicolon : [
          '1 + 1',
          '1 + 1;;'
        ],
        MissingBracket : [
          '1 + 1 )'
        ]
      }
      )
      if not exc_class:
        raise
      else:
        print(exc_class(u.get_context(inputCode), u.line, u.column).return_exception())
```

**Comment by MegaIng** [comment] 2020-08-10 20:20
Ok, should have asked for a minimal example. A small script that showcases only the parts relevant for this problem: The grammar and a string that throws an exception.

**Comment by erezsh** [comment] 2020-08-10 20:44
I don't think you're doing what you think you're doing. By having `MissingBracket` twice in your dictionary, you're just overwriting the first key.

Lark's error handling definitely could use an upgrade. My impression is that the `match_example()` method is fundamentally insufficient for serious error handling, but I'm open to suggestions.

**Comment by techpixel** [comment] 2020-08-10 21:21
@erezsh 
Whoops! My mistake. Also another alternative to higher importance is maybe correct examples? Like don't match for `1 + 1;`. In my case it would be `MissingSemicolon` that would have a specific match to show that `1 + 1 )` is correct but have `MissingBracket` have `1 + 1 )` incorrect.

@MegaIng 
Current Grammar:
```
NUMBER : /[0-9]+/
FLOAT : /[0-9]+\.[0-9]+/

?start : program*

?program : expr ";"

?expr : term
      | expr "+" term -> add
      | expr "-" term -> sub

?term : NUMBER
      | FLOAT
      | "-" NUMBER -> neg
      | term "*" term -> mul
      | term "/" term -> div
      | term "^" term -> pow
      | "(" expr ")"

%ignore " "
```

If I input `1 + 1` it should raise an UnexpectedInput, match examples, and return a `MissingSemicolon` error. However, I would get a `MissingBracket` instead.

**Comment by erezsh** [comment] 2020-08-10 21:31
As a simple fix, just swapping the order would solve it, no?

So I assume the probkem is that sometimes you want `MissingBracket` to take precedence?

**Comment by techpixel** [comment] 2020-08-10 21:38
@erezsh  Only some of the examples in MissingBracket have to take precedence. If I were to swap it, then `MissingSemicolon` would cause an error with `1 + 1 )` because it thinks that there has to be a semicolon between `1` and `)`.

**Comment by MegaIng** [comment] 2020-08-10 21:48
I simple change in the code would be to replace the dictionary with an iterable of tuple (key, examples). This would allow to have duplicate keys.

**Comment by techpixel** [comment] 2020-08-10 21:51
@MegaIng That idea works too.

**Comment by MegaIng** [comment] 2020-08-12 08:02
Ok, I am playing around with the code and made a discovery: The Problem is that the `Exception.token` value is the `$END` token. Since we just match on that token, `( 1 + 1` and `1 + 1` are equivalent. So no, there is no easy fix for this.

**Comment by erezsh** [comment] 2020-08-12 08:17
What if we match on the previous token instead?

**Comment by MegaIng** [comment] 2020-08-12 08:19
Doesn't help. We have to check like 3 tokens back. I have no idea how lalr works, but I expected for this information to be encoded in the state, but it is encoded in the parse stack (I think).

**Comment by erezsh** [comment] 2020-08-12 08:47
@MegaIng Have you seen the new puppet interface I added? It lets you step interactively through the LALR states, and it comes with every `UnexpectedToken` exception.

**Comment by MegaIng** [comment] 2020-08-12 09:06
@erezsh But something isn't correct with the puppet creation. When I pass in `(1+1` and then view the puppet choices, I don't see `)`, but `;` is supposedly valid.

**Comment by MegaIng** [comment] 2020-08-12 09:09
Ok, the problem is that the same puppet is returned even in different exceptions without changing the states. So consecutive calls to `parse` will raise errors with the same puppet even if the state is different and so making `puppet.choices` return wrong things.

**Comment by MegaIng** [comment] 2020-08-12 09:13
OK, something here is broken: with the grammar, calling `parser.parse("(1+1")` returns Semicolon as one of the expected tokens:

```
parser.parse("(1+1")
Traceback (most recent call last):
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 60, in get_action
    return states[state][token.type]
KeyError: '$END'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\tramp\PycharmProjects\lark\lark\lark.py", line 400, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parser_frontends.py", line 127, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parser_frontends.py", line 58, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 112, in parse
    _action, arg = get_action(token)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 67, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token($END, '') at line 1, column 4.
Expected one of: 
	* CIRCUMFLEX
	* STAR
	* PLUS
	* MINUS
	* SEMICOLON
	* RPAR
	* SLASH

```

**Comment by erezsh** [comment] 2020-08-12 09:18
If you think something is broken, perhaps we should take it to a new issue, where you can post some minimal example for me to look at.

**Closed** 2020-08-13 08:58 UTC
Labels: enhancement
