### ISSUE TITLE
RecursionError maximum recursion depth exceeded with more than 242 terminals

### ISSUE THREAD

**Issue by belerico** [lark-parser/lark#550] opened 2020-04-02 02:12 UTC
Hi, first i just wanna say thank you for this awesome package!
I'm using python3.8 and i'trying to parse an asciimath string and translate it to latex with the following grammar:
```python
r"""
start: i+ -> exp
csl: start ("," start)* ","?                    // csl = Comma Separated List
csl_mat: icsl_mat ("," icsl_mat)* ","?          // csl_mat = Comma Separated List for MATrices
icsl_mat: "[" start? ("," start)* ","? "]"      // icsl_mat = Internal Comma Separated List for MATrices
i: s -> exp_interm
    | s "/" s -> exp_frac
    | s "_" s -> exp_under
    | s "^" s -> exp_super
    | s "_" s "^" s -> exp_under_super
s: _l csl? _r -> exp_par
    | "[" csl_mat? "]" -> exp_bmat
    | "(" csl_mat? ")" -> exp_pmat
    | "(" csl_mat? ")" -> exp_pmat
    | "{{" csl_mat? "}}" -> exp_cmat
    | "|" csl_mat? "|" -> exp_vmat
    | "||" csl_mat? "||" -> exp_nmat
    | "{{" csl_mat? ")" -> exp_system
    | _u s -> exp_unary
    | _b s s -> exp_binary
    | _qs -> q_str
    | _c -> symbol
_c: LETTER
    | NUMBER
    | /d[A-Za-z]/
    | _ls
!_l: {} // left parenthesis
!_r: {} // right parenthesis
!_b: {} // binary functions
!_u: {} // unary functions
!_ls: {} // LaTeX Symbols
_qs: "\"" /(?<=").+(?=")/ "\"" // Quoted String
%import common.WS
%import common.LETTER
%import common.NUMBER
%ignore WS
""".format(left, right, binary, unary, latex)
```
where latex is a string containing all the asciimath symbols to be translated, e.g. latex = `"infty" | "aleph"| ":." | "therefore" | ":'" | "because" | "..."` and is created from a dictionary of more than 200 asciimath strings.
The problem is that if latex string is created from more than 242 elements, i get this error:
```
Traceback (most recent call last):
  File "/home/belerico/Desktop/projects/sciq/parser.py", line 398, in <module>
    parser = ASCIIMath2Tex(
  File "/home/belerico/Desktop/projects/sciq/parser.py", line 333, in __init__
    self.parser = Lark(
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/lark.py", line 182, in __init__
    self.terminals, self.rules, self.ignore_tokens = self.grammar.compile(self.options.start)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/load_grammar.py", line 451, in compile
    rule_defs = deepcopy(self.rule_defs)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/tree.py", line 117, in __deepcopy__
    return type(self)(self.data, deepcopy(self.children, memo))
  ... ...
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/copy.py", line 137, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
```
At first i thought that i've got some recursive terminal, but i tested even creating latex string from a dictionary like `smb = {"\"" + str(i) + "\"": str(i) for i in range(243)}`.
`sys.setrecursionlimit(1024)` seems to temporarily resolve the issue

**Comment by erezsh** [comment] 2020-04-02 07:40
Please provide a script that produces this error.

**Comment by MegaIng** [comment] 2020-04-02 07:42
The problem is that the way alternatives (`a | b`) are currently implemented is that they are nested. So `a | b | c` is actually parsed as `(a | b) | c`, creating a long chain of Nodes that goes on a long time. if this is copied,  all Nodes have to be copied, reaching the recursion limit.

**Comment by belerico** [comment] 2020-04-02 09:47
> Please provide a script that produces this error.

Yeah, sorry i haven't done it before.
```python
import lark

lark.Lark(r"""
    start: {}
""".format(
    "|".join(["\"" + str(i) + "\"" for i in range(244)])
))
```

**Comment by erezsh** [comment] 2020-04-02 11:11
Pushed a fix to `master`. Let me know if it works.

Thanks for the compliment!

**Comment by erezsh** [comment] 2020-04-02 11:29
However, maybe the best solution, in terms of parser performance, is to put all of your strings into a single terminal, and resolve it afterwards with a dictionary.

**Comment by belerico** [comment] 2020-04-02 11:34
> Pushed a fix to `master`. Let me know if it works.

Yeah, it works!

> However, maybe the best solution, in terms of parser performance, is to put all of your strings into a single terminal, and resolve it afterwards with a dictionary.

What do you mean with `put all of your strings into a single terminal`? Sorry for the dumb question but i'm a newbie in the parser/grammar field :)

**Comment by erezsh** [comment] 2020-04-02 11:56
Instead of 

    latex: "infty" | "aleph"| ":." | "therefore" | ":'" | "because" | "..."

do


    LATEX: "infty" | "aleph"| ":." | "therefore" | ":'" | "because" | "..."

Now LATEX is a single regexp, and isn't handled by the parser, so it should be faster.

**Comment by erezsh** [comment] 2020-04-02 12:00
Hmm never mind. I tried it myself and it seems that Python isn't immune to this either:
```python
   p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Python38\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Python38\lib\sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Python38\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Python38\lib\sre_parse.py", line 495, in _parse
    subpattern = SubPattern(state)
RecursionError: maximum recursion depth exceeded
```

Oh well :D

**Comment by erezsh** [comment] 2020-04-02 12:01
So, if grammar init takes too long, you can either use `cache=True` or split into multiple terminals, as apparently one can't be easily supported.

**Comment by belerico** [comment] 2020-04-02 12:09
> Instead of
> 
> ```
> latex: "infty" | "aleph"| ":." | "therefore" | ":'" | "because" | "..."
> ```
> 
> do
> 
> ```
> LATEX: "infty" | "aleph"| ":." | "therefore" | ":'" | "because" | "..."
> ```
Oh yeah, I've got it! I put all the terminals in a rule so that I don't have to disambiguate between terminals like `in` or `int`, but I don't know if it's only a workaround and there're better ways to disambiguate between terminals that are prefixes of other terminals.

**Comment by belerico** [comment] 2020-04-02 12:22
> So, if grammar init takes too long, you can either use `cache=True` to reduce subsequent loads, or split it into multiple terminals, as apparently a single long one can't be easily supported.

Yeah, even this code results in a RecursionError

```import lark

lark.Lark(r"""
    start: L
    L: {}
""".format(
    "|".join(["\"" + str(i) + "\"" for i in range(244)])
))```

**Comment by erezsh** [comment] 2020-04-02 12:29
Yes. I can fix it in Lark, but even then Python regexps will crash, so it isn't worth it.

**Comment by erezsh** [comment] 2020-04-03 08:28
Happy to help.

**Closed by erezsh** 2020-04-03 08:28 UTC
