### ISSUE TITLE
Standalone parser is not deterministic

### ISSUE THREAD

**Issue by Kyuuhachi** [lark-parser/lark#1341] opened 2023-09-22 15:27 UTC
**Describe the bug**

I want to keep a standalone parser in my repo, to make it easy to use without any dependencies. But even rebuilding exactly the same grammar produces a different parse table, which makes git diff unhappy. I presume this is because `set()` is unordered.

**To Reproduce**

The simplest possible grammar: an empty start rule, `start:`. Then compile it twice and compare the output, `diff =(python -m lark.tools.standalone a.g) =(python -m lark.tools.standalone a.g)`.

```diff
3157c3157
< ... 'parser': {'tokens': {0: 'start', 1: '$END'}, 'states': {0: {}, 1: {0: (0, 0), 1: (1, {'@': 0})}}, 'start_states': {'start': 1}, 'end_states': {'start': 0}}, ...
---
> ... 'parser': {'tokens': {0: 'start', 1: '$END'}, 'states': {0: {0: (0, 1), 1: (1, {'@': 0})}, 1: {}}, 'start_states': {'start': 0}, 'end_states': {'start': 1}}, ...
```
(I cut off some irrelevant parts)

**Comment by MegaIng** [comment] 2023-09-22 16:02
Duplicate of https://github.com/lark-parser/lark/issues/1194

**Comment by aspizu** [comment] 2023-10-25 18:49
what u doin here

**Closed** 2024-03-29 11:14 UTC
