### ISSUE TITLE
Collecting examples of inconsistent parsing by Earley (non-deterministic results)

### ISSUE THREAD

**Issue by jtrakk** [lark-parser/lark#419] opened 2019-08-01 19:44 UTC
@erezsh [has indicated](https://github.com/lark-parser/lark/issues/343#issuecomment-517050980) it'd be helpful for us to provide examples of random parsing, and the simpler the better. I'll kick it off.

Please include:

- grammar
- input text
- parse trees
- Python version
- Lark version
- the values of PYTHONHASHSEED that generate different parse trees.

**Comment by jtrakk** [comment] 2019-08-01 19:46
This is a reduced version of my attempt at emulating [jo](https://github.com/jpmens/jo/blob/master/jo.md) with Lark.

```py
import lark

grammar = r"""
?start: sequence

?value: object
  | SIGNED_NUMBER      -> number
  | "null"             -> null

object : "{" [pair ("," pair)*] "}"
pair   : string ":" value
string : ESCAPED_STRING

?thing : value
       | eqpair
       | eqnull




name : NAME
eqpair : (value|name) "=" value

eqnull : (thing | name ) "="

sequence : thing+



%import common.ESCAPED_STRING
%import common.CNAME -> NAME
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS


"""


parser = lark.Lark(grammar)

text = 'a=1'

print(parser.parse(text).pretty())

```
```bash

PYTHONHASHSEED=1 python example.py
sequence
  eqpair
    name	a
    number	1


PYTHONHASHSEED=3 python example.py
sequence
  eqnull
    name	a
  number	1

```

**Comment by erezsh** [comment] 2019-08-10 12:40
Another example is given at #388: 

```python
from lark import Lark

numbergrammar = """
start: number*
number: hex_number | decimal_number
hex_number.100: size? HEX_BASE HEX_VALUE
decimal_number: UNSIGNED_NUMBER
size.100: NON_ZERO_UNSIGNED_NUMBER
NON_ZERO_UNSIGNED_NUMBER: /[1-9][0-9_]*/
FIXED_POINT_NUMBER: /([0-9][0-9_]*\.[0-9][0-9_]*)/
UNSIGNED_NUMBER: /([0-9][0-9_]*)/
HEX_VALUE: /([0-9a-fA-FxXzZ][0-9a-fA-F_xXzZ]*)/
HEX_BASE: /'([sS])?[hH]/

%import common.WS
%ignore WS
"""

testparser = Lark(numbergrammar)

test_numbers = """
16'habcd
"""

parsed_numbers = testparser.parse(test_numbers)
print(parsed_numbers.pretty())                     
```

**Comment by night199uk** [comment] 2019-08-17 16:03
will try and take a look at these tomorrow.

**Comment by night199uk** [comment] 2019-08-18 00:42
> This is a reduced version of my attempt at emulating [jo](https://github.com/jpmens/jo/blob/master/jo.md) with Lark.
> 
> Running Python 3.7.1, lark 0.7.2
> 

So I took a look at this one first. Check out the debug=True|False PR I've just added to Lark, as it's really useful to dump the SPP forest using pydot to analyze problems like this.

The problem is some non-determinism in the way the PackedNodes are added to the SymbolNodes.
[IMG]http://i67.tinypic.com/11c42ko.png[/IMG]
Note the ambiguous PackedNodes labelled _anon_plus_1, 3, -inf, 11.

Checking repr(PackedNode), that is: symbol, start, priority, rule.order. That is the same sort key used for selecting the priority of ambiguous PackedNodes, by PackedNode.sort. Priority is the value set on the rule priority (e.g. eqnull.100 = 100), in this case since there are no priorities set on the tree is -inf. Rule.order should be the order amongst various options of a rule for this match. e.g.
x:    a   <- rule.order = 0
     | b  <- rule.order = 1
     | c  <- rule.order = 2

Given that both PackedNodes are set to have rule.order of 11 (and I don't see any rules here with 11 possible candidates), something looks to be broken with rule.order. This is generated within the Grammar analyzer which I know saw some work since Earley went in, so I'm not sure if this was an oversight. I'll try and find the bug if that's what it is and see if I can fix it.

**Comment by jtrakk** [comment] 2019-08-18 01:07
@night199uk  The image link is broken

**Comment by jtrakk** [comment] 2019-08-18 01:18
@night199uk The image link is broken.

**Comment by night199uk** [comment] 2019-08-18 01:41
Updated. The issue (and hopefully all Earley non-determinism) is fixed by PR #428 anyway. :-)

**Comment by erezsh** [comment] 2019-08-18 08:41
Seems to be solved! @jtrakk Care to verify?

**Comment by jtrakk** [comment] 2019-08-18 18:34
> Seems to be solved! @jtrakk Care to verify?

Confirmed, works for me. Thanks @night199uk and @erezsh!

**Comment by erezsh** [comment] 2019-08-20 08:58
Alright, I consider this saga closed, until someone points otherwise. Thanks for everyone involved!

**Closed by erezsh** 2019-08-20 08:58 UTC
