### ISSUE TITLE
Help with lark precedence

### ISSUE THREAD

**Issue by pcanelas** [lark-parser/lark#615] opened 2020-07-08 18:45 UTC
Hello,

I have been trying to work with lark on a project, but there have been some problemas with the precedence. Lets say I have the following piece of the grammar:
```
my_import : "import" PATH ";"                    -> regular_import
          | "import" CNAME "from" PATH ";"       -> function_import


PATH : ((".." | CNAME ) "/")* CNAME
```

If I try to provide, for example, the following text: `import function from library` it raises an error:

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.8/site-packages/lark/lexer.py", line 378, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "/home/paulo/.local/lib/python3.8/site-packages/lark/lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for 'f' at line 1 col 16

import library from fun;
               ^

Expecting: {'SEMICOLON'}

Previous tokens: Token(PATH, 'library')
``` 

I have tried to invert the order that the options appear on the rule my_import, but I keep having the same issue. Was wondering if you could tell me what I'm doing wrong...

Thank you!
Paulo

**Comment by MegaIng** [comment] 2020-07-08 19:41
Please create an [mcve](https://stackoverflow.com/help/minimal-reproducible-example). We especially need to information what options you are passing Lark, what imports you are doing and what you are ignoring. Just create a small python script that fails with this error message.

**Comment by pcanelas** [comment] 2020-07-08 20:06
Hello Megalng,

The following python script should give you the previous error:

```
from lark import Lark, Transformer

grammar = """
start : my_import

my_import : "import" PATH ";"                    -> regular_import
          | "import" CNAME "from" PATH ";"       -> function_import

%import common.WS
%import common.CNAME

PATH : ((".." | CNAME ) "/")* CNAME

%ignore WS
"""

class ImportTree(Transformer):
    
    def function_import(self, args):
        print(f"import {args[1]} from {args[0]};")

    def regular_import(self, args):
        print(f"import {args[0]};")

imp_parser = Lark(grammar, parser='lalr', start="start", transformer=ImportTree())
imp = imp_parser.parse

def test():
    imp("import library;")
    imp("import test from library;")

if __name__ == '__main__':
    test()
```

**Comment by erezsh** [comment] 2020-07-08 20:10
Your definition of `PATH` includes `CNAME`.

The LALR lexer cannot resolve collisions between regexps for you. Use Earley, or disambiguate your terminals.

**Comment by erezsh** [comment] 2020-07-08 20:11
Btw, a reproducing example include *everything*. Yours will not produce an error, because you omitted the initialization of Lark.

**Comment by pcanelas** [comment] 2020-07-08 20:13
Understood.

Thank you for the help erezsh

**Comment by erezsh** [comment] 2020-07-08 20:38
You're welcome. I'm closing the issue, but you can ask more questions if you need to.

**Closed by erezsh** 2020-07-08 20:38 UTC
Labels: question
