### ISSUE TITLE
error reporting with match_examples broken with earley when lexer is dynamic

### ISSUE THREAD

**Issue by ornariece** [lark-parser/lark#760] opened 2020-11-16 13:59 UTC
Trying to match error examples doesn't work when using earley with the dynamic lexer, seemingly because the parser state is not passed to the UnexpectedCharacters object. The assertion on the state not being None fails.

From what i gather, in https://github.com/lark-parser/lark/blob/0.11.0/lark/parsers/xearley.py#L116, a state should be passed to the UnexpectedCharacters. Not sure where to get the state from though, hence why no PR from me.

**Comment by erezsh** [comment] 2020-11-16 15:20
I'm sorry if you were misled by the docs. The `match_examples()` function only worked with LALR until now.

But, you inspired me to try and fix it. I pushed a new branch, `earley_error_reporting`. Can you check if it works for you?

**Comment by ornariece** [comment] 2020-11-16 19:58
it now works with earley, but it breaks with lalr for some strings (i'm using both earley and lalr, for 2 different grammars). the same assertion is raised, on the state being None.

**Comment by erezsh** [comment] 2020-11-16 20:09
Can you provide a minimal example where it fails with LALR?

**Comment by ornariece** [comment] 2020-11-16 20:24
here is a simplified grammar:
```
start: subject "." test operator value
test: CNAME
value: CNAME
CNAME: ("_"|"."|LETTER) ("_"|"."|LETTER|DIGIT)*
num: NUMBER
!subject: "self"
!operator: "=="

%import common.LETTER
%import common.DIGIT
%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
```

and here are the 2 examples where it fails to match the errors (`AssertionError: Not supported for this exception`):
`self.a =< b`
`self.a == b &^ self.c == d`

**Comment by ornariece** [comment] 2020-11-21 16:54
hi, any update on this? not trying to pressure you, i'd just want to know if i should move on to a workaround

**Comment by MegaIng** [comment] 2020-11-21 17:52
`match_examples` only works for `UnexpectedToken` and `UnexpectedEOF`, not for `UnexpectedCharacters`. Make sure you use it on a exception of those types.

**Comment by ornariece** [comment] 2020-11-21 18:43
well i'm using it on ``UnexpectedInput``. previously, in 0.10.0, it wasn't throwing an ``UnexpectedCharacter`` (or if it did it didn't prevent the error from getting matched). it seems 0.11.0 introduced this behavior. is it intended?

**Comment by MegaIng** [comment] 2020-11-21 18:53
No. It doesn't work in 0.10.0. It doesn't work with the same exception for the last three years.

**Comment by ornariece** [comment] 2020-11-21 19:26
i'm using the exact same code in 0.10.0 and the assertion isn't raised. i've triple checked in both 0.10.0 and 0.11.0, and 0.10.0 doesn't raise the assertion while 0.11.0 does. perhaps something changed in the match_examples() that now makes it throw an ``UnexpectedCharacter`` instead of an ``UnexpectedToken``?
would you like to take a look at my tree transformer or is that of no use?

**Comment by MegaIng** [comment] 2020-11-21 19:29
I am also using the exact code in 0.10.0 and the assertion is raised.

**Comment by ornariece** [comment] 2020-11-21 19:39
my bad, please excuse me, i have been testing this with my full syntax, not the simplified syntax i provided. here is the full syntax:
```
?start: conj ("||" conj)*
?conj: filter ("&&" filter)*
?filter: subject "." test additionals operator value | "(" start ")"
test: CNAME
!value: num | bool | CNAME | (CNAME ":" CNAME)
CNAME: ("_"|"."|LETTER) ("_"|"."|LETTER|DIGIT)*
num: NUMBER
!bool: "true" | "false" | "True" | "False"
!subject: "block" | "other" | "parent" | "player" | "self" | "target"
!operator: "==" | "!=" | ">=" | "<=" | "<" | ">"
additional: CNAME ":" CNAME
additionals: "(" ((additional ",")* additional)? ")" |

%import common.LETTER
%import common.DIGIT
%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
```
and the examples for which it raises the assertion in 0.11.1 but not in 0.10.0:
``other.werwe=<eerrr``
``other.werwe(a: b)>=wewer &^ other.werwe(a: b)>=wewer``

**Comment by MegaIng** [comment] 2020-11-21 19:41
I still can not reproduce. Please give a full python script.

**Comment by MegaIng** [comment] 2020-11-21 19:44
Sorry, was an idiot. Can reproduce.

**Comment by MegaIng** [comment] 2020-11-21 19:50
Ok, @erezsh This is an unnoticed regression in the resumable changes. But it is quite easy to correct, espcially since we know have it easier to get access to the parser state.

@ornariece Yup, this is a bug. There was a redesign of the Lexer infrastructure, and we somehow missed this change.

**Comment by ornariece** [comment] 2020-11-21 19:53
ha, glad i could help; i was about to upload the script haha. are you going to make a release out of this? it'd be amazing if you could include the ``earley_error_reporting`` branch with it, if you think it's ready for release ofc

**Comment by erezsh** [comment] 2020-11-23 08:30
Changes have been merged to `master`.

@ornariece Since you found these issues, I'd appreciate if you make sure that everything works now.

**Comment by ornariece** [comment] 2020-11-23 17:56
@erezsh there seems to be a divergent behavior between usage with larl and usage with earley. here is a code that returns
```
FilterTrailingComma
FilterInvalidTest
FilterInvalidLogical
``` 
with larl (expected output), but
```
FilterNoValue
FilterNoValue
FilterUnbalancedParens
``` 
with earley.

```
from lark import Lark, UnexpectedInput


_parser = Lark(r"""
    ?start: conj ("||" conj)*
    ?conj: filter ("&&" filter)*
    ?filter: subject "." test additionals operator value | "(" start ")"
    test: CNAME
    !value: num | bool | CNAME | (CNAME ":" CNAME)
    CNAME: ("_"|"."|LETTER) ("_"|"."|LETTER|DIGIT)*
    num: NUMBER
    !bool: "true" | "false" | "True" | "False"
    !subject: "block" | "other" | "parent" | "player" | "self" | "target"
    !operator: "==" | "!=" | ">=" | "<=" | "<" | ">"
    additional: CNAME ":" CNAME
    additionals: "(" ((additional ",")* additional)? ")" |
    
    %import common.LETTER
    %import common.DIGIT
    %import common.NUMBER
    %import common.WS_INLINE
    
    %ignore WS_INLINE

    """, parser="lalr")

examples = {
    'FilterNoValue': [
        "self.has_tag(a: )==tagname",
        "self.has_tag(a)==tagname"
    ],
    'FilterUnbalancedParens': [
        "self.has_tag a: b)==tagname",
        "self.has_tag(a: b==tagname",
        "(self.has_tag==tagname && self.has_tag==tagname",
        "(self.has_tag==tagname || self.has_tag==tagname",
        "self.has_tag==tagname && self.has_tag==tagname)",
        "self.has_tag==tagname || self.has_tag==tagname)"
    ],
    'FilterTrailingComma': [
        "self.has_tag(a: b, c: d,)==tagname",
        "self.has_tag(a: b,, c: d)==tagname"
    ],
    'FilterInvalidTest': [
        "self.5has_tag(a: b)==tagname",
        "self.5has_tag==tagname"
    ],
    'FilterInvalidLogical': [
        "(self.has_tag==tagname |& self.has_tag==tagname)",
        "self.has_tag==tagname ^ self.has_tag==tagname"
    ]
}

try:
    _parser.parse("other.werwe(a: b,)>=eerrr")
except UnexpectedInput as u:
    print(u.match_examples(_parser.parse, examples))

try:
    _parser.parse("other.45werwe(a: b)>=wewer")
except UnexpectedInput as u:
    print(u.match_examples(_parser.parse, examples))

try:
    _parser.parse("other.werwe(a: b)>=wewer &^ other.werwe(a: b)>=wewer")
except UnexpectedInput as u:
    print(u.match_examples(_parser.parse, examples))
```

**Comment by MegaIng** [comment] 2020-11-23 18:02
That is to be expected. `match_examples` is a hack. It might be possible to improve this, but we will probably never get perfect results.

*In general* it is expected that lalr returns better results at the moment. This is in general a motto of this library: if possible, use lalr.

(note how what is returned for earley isn't wrong. It just isn't the correct problem at that point.)

There are improvements to be made. We can keep this issue open for that. But in it's basics, this is now working, although there are still wishes to be fulfilled.

**Comment by erezsh** [comment] 2020-11-23 20:50
So, I looked into it, and I think I made it better.

Actually, I think now Earley works too well, and can match more specifically than LALR. Oh well.

Pushed to `master`. Give it a go, @ornariece.

> match_examples is a hack

Yup, no argument there

**Comment by ornariece** [comment] 2020-11-25 21:54
still having issues with it. i'm just going to give you the whole syntax, as i'm getting nowhere trying to get a minimal example... problem with that grammar is that i can't compare the match_examples() results with those i'd get with lalr, because LALR(1) can't handle that grammar. here is the grammar and examples; i think the intended result of the print would have to be 'InvalidValue', not ''InvalidOperator':
```
from lark import Lark, UnexpectedInput


_parser = Lark(r"""
    CNAME: ("_"|"."|LETTER) ("_"|"."|LETTER|DIGIT)*
    !string: "'" ("_"|"."|LETTER) (":"|"_"|"."|LETTER|DIGIT)* "'"
    test: CNAME
    num: NUMBER
    !bool: "true" | "false" | "True" | "False"
    f_value: CNAME | num | bool
    m_value: num | bool | string
    !l_operator: "==" | "!=" | ">=" | "<=" | "<" | ">"
    !m_operator: "+" | "-" | "/" | "*"
    l_not: "!"
    m_not: "-"
    variable: "variable." test
    temp: "temp." test
    q_additionals: "(" [(cond ",")* cond] ")"
    query: "query." test [q_additionals]
    m_additionals: "(" (cond ",")* cond ")"
    math: "math." test m_additionals
    slot: "slot." test
    f_additional: CNAME ":" f_value
    f_additionals: ["(" ((f_additional ",")* f_additional)? ")"]
    filter: "filter." test f_additionals l_operator f_value
    ?assignable: variable | temp | "(" assignable ")"
    ?start: (assign ";")* [ret] | cond
    ?ret: "return" cond ";"
    ?assign: assignable "=" cond | "(" assign ")"
    ?cond: union ("?" union ":" union)*
    ?union: conj ("||" conj)*
    ?conj: l_eval ("&&" l_eval)*
    ?l_eval: m_eval (l_operator m_eval)*
    ?m_eval: (m_neg | l_neg) (m_operator (m_neg | l_neg))*
    ?m_neg: m_not? var
    ?l_neg: l_not? var
    ?var: query | variable | temp | math | slot | filter | m_value | "(" cond ")"
    %import common.LETTER
    %import common.DIGIT
    %import common.NUMBER
    %import common.WS_INLINE
    %ignore WS_INLINE
    """)

examples = {
    'InvalidOperator': [
        "1 =< 2",
        "1 % 2",
        'query.q =< v'
        "filter.has_tag=<tagname",
        "filter.has_tag(a: b)%tagname"
    ],
    'InvalidValue': [
        "filter.has_tag(a: b) == 5tagname",
        "filter.has_tag == 5tagname",
        'query.q == 45v'
    ]
}

try:
    _parser.parse('query.q == 45v')
except UnexpectedInput as u:
    print(u.match_examples(_parser.parse, examples))
```

**Comment by MegaIng** [comment] 2020-11-25 22:07
A tip: When you set the logging level of `lark.logger` to `DEBUG`, `match_examples` will give you a bit of extra information.

The problem here is (I think) that your grammar is to ambiguous and everything gets put in just a few `states` which are separated out at a later stage (e.g. at Tree generation). This means that the situations look the same. This is especially bad for `UnexpectedCharacters`, because there are no stronger method to recognize failures like there are for `UnexpectedToken`.

You could either try to rewrite your grammar to be lalr (that might be as easy as adding priorities, clearly structure your operators according to precedence, or it might be impossible).

Or you could try to use the fact that it is possible to specify 'priorities' in the examples:

```
examples = [
    ('InvalidValue', [
        'query.q == 45v'
    ]),
    ('InvalidOperator', [
        "1 =< 2",
        "1 % 2",
        'query.q =< v'
        "filter.has_tag=<tagname",
        "filter.has_tag(a: b)%tagname"
    ]),
    ('InvalidValue', [
        "filter.has_tag(a: b) == 5tagname",
        "filter.has_tag == 5tagname"
    ])
]
```

The examples will simply be tried from top to bottom. A dictionary is decent when you don't want to repeat stuff, since it is easier to read/write.

**Comment by ornariece** [comment] 2020-11-26 22:44
i've already tried priorities, and i couldn't make it do the trick. i'm a beginner with grammars though, so there is probably room for improvement.
it's not very pressing for me for now, but i will try to improve the grammar at some point, or, if it turns out to be impossible, put priorities in the examples. i'll get back to you either way. thanks for the help and the fixes, much appreciated

**Comment by erezsh** [comment] 2021-05-13 20:14
Closing since it's been a while. But feel free to continue the discussion.

**Closed by erezsh** 2021-05-13 20:14 UTC
