### ISSUE TITLE
IndexError in parse_tree_builder.py, release 0.10.0

### ISSUE THREAD

**Issue by grihabor** [lark-parser/lark#752] opened 2020-11-11 20:54 UTC
**Describe the bug**

I'm trying to parse a snippet and I get this error:
```
contrib/python/lark-parser/lark/lark.py:438: in parse
    return self.parser.parse(text, start=start)
contrib/python/lark-parser/lark/parser_frontends.py:215: in parse
    return self._parse(text, start)
contrib/python/lark-parser/lark/parser_frontends.py:58: in _parse
    return self.parser.parse(input, start, *args)
contrib/python/lark-parser/lark/parsers/earley.py:320: in parse
    return transformer.transform(solutions[0])
contrib/python/lark-parser/lark/parsers/earley_forest.py:353: in transform
    self.visit(root)
contrib/python/lark-parser/lark/parsers/earley_forest.py:295: in visit
    vpno(current)
contrib/python/lark-parser/lark/parsers/earley_forest.py:417: in visit_packed_node_out
    transformed = self.transform_packed_node(node, self.data[id(node)])
contrib/python/lark-parser/lark/parsers/earley_forest.py:559: in transform_packed_node
    return self._call_rule_func(node, children)
contrib/python/lark-parser/lark/parsers/earley_forest.py:521: in _call_rule_func
    return self.callbacks[node.rule](data)
contrib/python/lark-parser/lark/parse_tree_builder.py:124: in __call__
    filtered = children[i].children
E   IndexError: list index out of range
```

I can't figure out what's wrong, could you help me please?

**To Reproduce**

```python
l = Lark(open('golang.lark').read(), start='go_file', regex=True)
l.parse("""
package x
func evalFrameHash(frame FrameData) norm.Hash {
h := [4]byte{0x5b, 0xd1, 0xe9, 0x95}
for i, b := range frame.FrameData() {
    h[i%4] ^= b
}
return norm.Hash{Data: h}
""")
```

grammar is here https://gist.github.com/grihabor/2014488c65cde5a5ef71fd61c13a75d6

**Comment by erezsh** [comment] 2020-11-11 21:03
Please try the `master` version and see if it helps.

**Comment by MegaIng** [comment] 2020-11-11 21:03
I can't reproduce. Please make sure that you are actually using the most recent version (e.g. it should be 0.10.1).

**Comment by grihabor** [comment] 2020-11-11 21:14
@MegaIng As I can tell the latest release is 0.10.0

@erezsh master works, thank you! When the next release is coming?

**Comment by erezsh** [comment] 2020-11-11 21:32
Probably next week.

**Comment by charles-esterbrook** [comment] 2020-11-12 02:01
Cool. This looks like the same problem I reported in Gitter.

**Comment by ThatXliner** [comment] 2020-11-12 04:00
Close this issue?

**Closed** 2020-11-12 07:54 UTC

**Comment by erezsh** [comment] 2020-11-16 12:31
Lark `0.11.0` has been released.
